### ISSUE TITLE
Filters no longer collection pollution

### ISSUE THREAD

**Issue by Golrith** [thebrightspark/PollutantPump#3]
Since the update, the Filter blocks attached to the pumps are no longer filtering the pollution. As a result getting some nice dark pollution clouds around my pumps as they are concentrating it in a small area.

**Comment by thebrightspark** [comment]
Thanks for letting me know, I've tested myself and it does indeed seem that the filters aren't being used at all. Looks like it might be a bug in Pollution Of The Realms but I should be able to work around it.

**Comment by thebrightspark** [comment]
Raised the issue with the author of the mod:
https://minecraft.curseforge.com/projects/pollution-of-the-realms/issues/27

**Comment by thebrightspark** [comment]
Seems there's a deeper issue here with the way I interact with the filters... am trying to confirm with the author on this.

**Comment by EnderLanky** [comment]
If you are trying to get rid of carbon, you have to upgrade your filters (using anvil and leaves) to cope with it.

**Comment by thebrightspark** [comment]
After some testing to confirm it works correctly, what EnderLanky says is correct.
@Golrith make sure you upgrade your filter with both leaves and paper to filter all pollutants and it will work just as before.
