### ISSUE TITLE
Pipe recipe replaces Thermal's iron gear recipe

### ISSUE THREAD

**Issue by AveoCross** [thebrightspark/PollutantPump#8]
I have CoFH Thermal series mods and Pollutant Pump in my modpack. The issue is when i try to craft iron gears from Thermal i'm getting pump pipes. And i have no other way to craft iron gears. 
Is there any way to change pipe's recipe?

**Comment by thebrightspark** [comment]
Yeah just use CraftTweaker or there's another mod which allows you to switch between recipes with the same input that I can't remember the name of

**Comment by AveoCross** [comment]
Temporary fix for this is setting alternate recipe for non-basic gears in Thermal Foundation config. 
But it would be nice to have option for conflict-safe recipe in PollutantPump maybe.
